---
title: "Untitled"
output: html_document
date: "2025-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pmartR)
library(tidyr)
library(dplyr)
library(ggplot2)
library(patchwork)
library(pmartRdata)
```

```{r}

temp <- pep_object
temp <- group_designation(temp, "Phenotype")

```

```{r}

data_1 <- missingval_result(temp)$na.by.molecule
data_1$Missingness <- data_1$num_NA/(data_1$num_non_NA+data_1$num_NA)


group_df <- get_group_DF(temp)
edata <- temp$e_data
edata_cname_id <- 1


```

```{r}

plot(missingval_result(temp), temp)

plot(missingval_result(temp), temp, plot_type = "scatter")

plot(missingval_result(temp), temp, plot_type = "scatter", color_by = "Group")
plot(missingval_result(temp), temp, plot_type = "scatter", groups = T)

```

```{r}

e_data_long <- tidyr::pivot_longer(temp$e_data, !get_edata_cname(temp), 
                                   names_to = get_fdata_cname(temp))

f_data_merge <- left_join(e_data_long, group_df, by = get_fdata_cname(temp))

Lipid_group_means <- f_data_merge %>% 
  group_by_at(c(get_edata_cname(temp), "Group")) %>% 
  reframe(mean = mean(value, na.rm = T))


df <- as.data.frame(pivot_wider(Lipid_group_means, 
                                id_cols = get_edata_cname(temp), 
                                names_from = "Group", 
                                values_from = "mean"))

row.names(df) <- df[[get_edata_cname(temp)]]
df[[get_edata_cname(temp)]] <- NULL
dist_mat <- dist(df)
dist_mat[is.na(dist_mat)] <-0 ## since we're just getting a general order, this should be okish
res_hclust <- hclust(dist_mat)
order_biom <- rev(res_hclust$labels[res_hclust$order])

missmean <- left_join(Lipid_group_means, data_1, by = get_edata_cname(temp))

missmean <- arrange(missmean, mean)
missmean[[get_edata_cname(temp)]] <- factor(missmean[[get_edata_cname(temp)]], levels = unique(missmean[[get_edata_cname(temp)]]))

# missmean[[get_edata_cname(temp)]] <- factor(missmean[[get_edata_cname(temp)]], levels = order_biom)

```

```{r}
      
p1 <- ggplot(missmean, 
        aes(
        y = Peptide,
        x = Group,
        fill = mean
        )
       ) +
  geom_tile() +
  theme_bw() +
  labs(y = "Molecules", fill = "Mean (log10)") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_discrete(expand=c(0,0)) +
  scale_fill_distiller(palette = "Spectral", trans = "log10", na.value="white")

p2 <- ggplot(missmean, 
        aes(
        y = Peptide,
        x = "",
        fill = Missingness
        )
       ) +
  geom_tile() +
  theme_bw() +
  labs(y = "", x = "") +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank(), ) +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_discrete(expand=c(0,0)) +
  scale_fill_distiller(palette = "PuOr", na.value= "green")


wrap_plots(p1, p2, ncol = 2, widths = c(20, 1), guides = "collect")


```

```{r}


e_meta_merge <- left_join(data_1, temp$e_meta, by = get_edata_cname(temp))


#e_meta_merge <- left_join(data_1, temp$e_meta, by = get_edata_cname(temp))[1:330,]

#e_meta_merge$Group <- as.character(1:330)

ggplot(
  e_meta_merge,
  aes(
    x = Missingness,
    y = Row
    )
) +
  geom_point() +
  theme_bw()

ggplot(
  e_meta_merge,
  aes(
    x = Missingness,
    y = RazorProtein
    )
) +
  geom_point() +
  theme_bw()


```



```{r}


levels <- unique(group_df$Group)

indices_list <- vector(
  mode = "list",
  length = length(levels)
)

for (i in 1:length(levels)) {
  # Extract the column indices for the ith group. This will be used to
  # subset e_data.
  inds <- which(group_df$Group == levels[i])
  indices_list[[i]] <- inds
}

# Calculate the mean intensity for each molecule by group. NaN can appear if
# an entire row has all NA values.
mean_by_group <- lapply(indices_list,
  function(x, temp_edata) rowMeans(temp_edata[x],
    na.rm = TRUE
  ),
  temp_edata = edata[, -edata_cname_id]
)

names(mean_by_group) <- levels

mean_intensity <- do.call(cbind, mean_by_group)

```





```{r}

plot_data <- cbind(num_missing_vals, mean_intensity)
plot_data <- as.data.frame(check.names = FALSE, plot_data)
plot_data <- plot_data %>%
  tidyr::pivot_longer(
    -num_missing_vals,
    cols_vary = "slowest",
    names_to = "variable",
    values_to = "value"
  ) %>% dplyr::mutate(
    variable = factor(
      variable,
      levels = names(plot_data)[
        -which(names(plot_data) == "num_missing_vals")
      ]
    )
  ) %>% data.frame

# Start the scatter plot when the group_DF attribute is present.
p <- ggplot2::ggplot(
  dplyr::filter(plot_data, !is.na(value)),
  ggplot2::aes(
    value,
    num_missing_vals
  )
) +
  ggplot2::geom_point(ggplot2::aes(color = variable),
    size = point_size
  )


```


```{r pressure, echo=FALSE}
ggplot(sample, aes(x = status, y = score)) + 
geom_boxplot(aes(fill = status), alpha = .2) +
geom_line(aes(group = name)) + 
geom_point(size = 2) + 
facet_wrap(~ test)
```

