```{r}
library(devtools)
library(pmartRdata)
document("~/Git_Repos/pmartR/")
load_all("~/Git_Repos/pmartR")
```

## Abundance Boxplots

#### Expression Matrix Only

Cognostics must be: N, Mean, Median, CV 

```{r}
trelliData1 <- as.trelliData.edata(e_data = pep_edata,
                                  edata_cname = "Peptide",
                                  omics_type = "pepData")

# Should return sample count, and mean, median, and cv abundance
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>% 
   trelli_abundance_boxplot(test_mode = TRUE, 
                            test_example = 1:10, 
                            cognostics = c("count", "mean abundance", "median abundance", "cv abundance"))

# Should return sample count, mean abundance, and median abundance
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>% 
   trelli_abundance_boxplot(test_mode = TRUE, 
                            test_example = 1:10, 
                            cognostics = c("count", "mean abundance", "median abundance"))

# Should return sample count and mean abundance
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>% 
   trelli_abundance_boxplot(test_mode = TRUE, 
                            test_example = 1:10)

# Should return sample count, and mean, median, and cv abundance
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>% 
   trelli_abundance_boxplot(test_mode = TRUE, 
                            test_example = 1:10, 
                            cognostics = c("count", "mean abundance", "median abundance", "cv abundance", "anova p-value"))

# Should return biomolecule count, and mean, median, and cv abundance
trelli_panel_by(trelliData = trelliData1, panel = "Sample") %>% 
   trelli_abundance_boxplot(test_mode = TRUE, 
                            test_example = 1:10, 
                            include_points = FALSE,
                            cognostics = c("count", "mean abundance", "median abundance", "cv abundance", "anova p-value"))
```

#### Grouping Information Included

```{r}
# Transform the data
omicsData <- edata_transform(omicsData = pep_object, data_scale = "log2")

# Group the data by condition
omicsData <- group_designation(omicsData = omicsData, main_effects = c("Phenotype"))

# Apply the IMD ANOVA filter
imdanova_Filt <- imdanova_filter(omicsData = omicsData)
omicsData <- applyFilt(filter_object = imdanova_Filt, omicsData = omicsData, min_nonmiss_anova=2)

# Normalize my pepData
omicsData <- normalize_global(omicsData, "subset_fn" = "all", "norm_fn" = "median", "apply_norm" = TRUE, "backtransform" = TRUE)

# Implement the IMD ANOVA method and compute all pairwise comparisons (i.e. leave the `comparisons` argument NULL)
statRes <- imd_anova(omicsData = omicsData, test_method = 'combined')

# Generate the trelliData object 
trelliData2 <- as.trelliData(omicsData = omicsData)
trelliData3 <- as.trelliData(statRes = statRes)   
trelliData4 <- as.trelliData(omicsData = omicsData, statRes = statRes)
```

```{r}
# Should return sample count and mean abundance per group
trelli_panel_by(trelliData = trelliData2, panel = "Peptide") %>% 
   trelli_abundance_boxplot(test_mode = TRUE, 
                            test_example = 1:10)

# Should return mean abundance per group
trelli_panel_by(trelliData = trelliData2, panel = "Peptide") %>%
  trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10, cognostics = c("mean abundance", "median abundance", "anova p-value"))

# Should return no cognostics 
trelli_panel_by(trelliData = trelliData2, panel = "Peptide") %>%
  trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10, cognostics = c("median abundance", "anova p-value"))

# Should return biomolecule count and mean abundance 
trelli_panel_by(trelliData = trelliData2, panel = "SampleID") %>%
  trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10, include_points = F)

# Should return biomolecule count and mean abundance per biomolecule class
trelli_panel_by(trelliData = trelliData2, panel = "RazorProtein") %>%
     trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10)
```

#### Statistics Included 

```{r}
# Stats only should error out 
#trelli_panel_by(trelliData = trelliData3, panel = "Peptide") %>% 
#  trelli_abundance_boxplot()

# Should return sample count and mean abundance per group
trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>% 
  trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10)

# Should return sample count and mean abundance per group, and anova p value and fold change
# per comparison
trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>% 
  trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10,
                           cognostics = c("count", "mean abundance", "median abundance", "cv abundance", "anova p-value", "fold change"))

# Should return biomolecule count and mean abundance 
trelli_panel_by(trelliData = trelliData4, panel = "SampleID") %>% 
  trelli_abundance_boxplot(test_mode = TRUE, test_example = 1:10, include_points = FALSE,
                           cognostics = c("count", "mean abundance", "median abundance", "cv abundance", "anova p-value", "fold change"))

# Should return biomolecule count and mean abundance 
trelli_panel_by(trelliData = trelliData4, panel = "RazorProtein") %>% 
  trelli_abundance_boxplot(cognostics = c("count", "mean abundance", "median abundance", "cv abundance", "anova p-value", "fold change"),
                           test_mode = TRUE, test_example = 1:10)
```

## Abundance Histograms

```{r}
# Should return sample count, and mean, median, cv, and skew abundance
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>% 
     trelli_abundance_histogram(test_mode = TRUE, test_example = 1:10)

# Should return median and skew abundance
trelli_panel_by(trelliData = trelliData2, panel = "Peptide") %>% 
     trelli_abundance_histogram(test_mode = TRUE, test_example = 1:10,
                                cognostics = c("median abundance", "skew abundance"))

# Should error out 
#trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>% 
#     trelli_abundance_histogram(test_mode = TRUE, test_example = 1:10,
#                                cognostics = c("sample count", "anova p-value"))

# Should return cv abundance
trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>% 
     trelli_abundance_histogram(test_mode = TRUE, test_example = 1:10,
                                cognostics = c("cv abundance"))
```

## Abundance Heatmaps

```{r}
# Should return sample count, mean abundance, and biomolecule count
trelli_panel_by(trelliData = trelliData2, panel = "RazorProtein") %>%
  trelli_abundance_heatmap(test_mode = TRUE, test_example = 1:10)

# Should return only biomolecule count
trelli_panel_by(trelliData = trelliData4, panel = "RazorProtein") %>%
  trelli_abundance_heatmap(cognostics = "biomolecule count", test_mode = TRUE, test_example = 1:10)

# Should return only mean abundance
trelli_panel_by(trelliData = trelliData4, panel = "RazorProtein") %>%
  trelli_abundance_heatmap(cognostics = "mean abundance", test_mode = TRUE, test_example = 1:10)
```

## Missingness Barplots

#### Expression data only

```{r}
# Should return total sample count, observed sample count, and observed sample proportion
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10)

# Should return observed sample proportion
trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = "observed proportion")

# Should return total biomolecule count, observed biomolecule count, and observed biomolecule proportion
trelli_panel_by(trelliData = trelliData1, panel = "Sample") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10)

# Should return total biomolecule count
trelli_panel_by(trelliData = trelliData1, panel = "Sample") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = "total count")
```

#### Add grouping data

```{r}
# Should return total sample count, observed sample count, and observed sample proportion per group
trelli_panel_by(trelliData = trelliData2, panel = "Peptide") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = "observed proportion")

# Should return total biomolecule count, observed biomolecule count, and observed biomolecule proportion
trelli_panel_by(trelliData = trelliData2, panel = "SampleID") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10)

# Should return no cognostics, as no stats data was supplied
trelli_panel_by(trelliData = trelliData2, panel = "SampleID") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = "g-test p-value")
```

##### Add statistics data 

```{r}
# Statistics data only. Should return total sample count, observed sample count, 
# and observed sample proportion per group
trelli_panel_by(trelliData = trelliData3, panel = "Peptide") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10)

# Statistics data only. Should return total sample proportion, and g-test p-value.
trelli_panel_by(trelliData = trelliData3, panel = "Peptide") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = c("observed proportion", "g-test p-value"))

# Should return total sample count and g-test p-value.
trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = c("total count", "g-test p-value"))

# Should have no cognostics
trelli_panel_by(trelliData = trelliData4, panel = "SampleID") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = c("g-test p-value"))

# Should have observed biomolecule count, total biomolecule count, and observed 
# biomolecule proportion
trelli_panel_by(trelliData = trelliData4, panel = "RazorProtein") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10)

# Should have observed biomolecule proportion.
trelli_panel_by(trelliData = trelliData4, panel = "RazorProtein") %>%
  trelli_missingness_bar(test_mode = TRUE, test_example = 1:10, cognostics = c("observed proportion", "g-test p-value"))
```

## Foldchange Bar

Requires only a statRes object

```{r}
# Should return fold change and anova p-value
trelli_panel_by(trelliData = trelliData3, panel = "Peptide") %>%
  trelli_foldchange_bar(test_mode = TRUE, test_example = 1:10)

# Should return only anova p-value
trelli_panel_by(trelliData = trelliData3, panel = "Peptide") %>%
  trelli_foldchange_bar(test_mode = TRUE, test_example = 1:10, cognostics = "anova p-value")

# Should error out when no stats are included
#trelli_panel_by(trelliData = trelliData1, panel = "Peptide") %>%
#  trelli_foldchange_bar(test_mode = TRUE, test_example = 1:10, cognostics = "anova p-value")
#trelli_panel_by(trelliData = trelliData2, panel = "Peptide") %>%
#  trelli_foldchange_bar(test_mode = TRUE, test_example = 1:10, cognostics = "anova p-value")

# Should return fold change and anova p-value
trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>%
  trelli_foldchange_bar(test_mode = TRUE, test_example = 1:10)

# Should return fold change
trelli_panel_by(trelliData = trelliData4, panel = "Peptide") %>%
  trelli_foldchange_bar(test_mode = TRUE, test_example = 1:10, cognostics = "fold change")
```

## Foldchange Boxplot

```{r}




```






