# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

anova_cpp <- function(data, gp, unequal_var, df_red) {
    .Call('_pmartRqc_anova_cpp', PACKAGE = 'pmartRqc', data, gp, unequal_var, df_red)
}

count_missing_cpp <- function(data, gp) {
    .Call('_pmartRqc_count_missing_cpp', PACKAGE = 'pmartRqc', data, gp)
}

proj_mat_cpp <- function(X, ngroups) {
    .Call('_pmartRqc_proj_mat_cpp', PACKAGE = 'pmartRqc', X, ngroups)
}

project_to_null_cpp <- function(data_mat, Xmatrix, ngroups) {
    .Call('_pmartRqc_project_to_null_cpp', PACKAGE = 'pmartRqc', data_mat, Xmatrix, ngroups)
}

fold_change_diff <- function(data, C) {
    .Call('_pmartRqc_fold_change_diff', PACKAGE = 'pmartRqc', data, C)
}

fold_change_ratio <- function(data, C) {
    .Call('_pmartRqc_fold_change_ratio', PACKAGE = 'pmartRqc', data, C)
}

fold_change_logbase2 <- function(data, C) {
    .Call('_pmartRqc_fold_change_logbase2', PACKAGE = 'pmartRqc', data, C)
}

fold_change_diff_na_okay <- function(data, C) {
    .Call('_pmartRqc_fold_change_diff_na_okay', PACKAGE = 'pmartRqc', data, C)
}

fold_change_diff_copy <- function(data, C) {
    .Call('_pmartRqc_fold_change_diff_copy', PACKAGE = 'pmartRqc', data, C)
}

group_comparison_anova_cpp <- function(means, sizes, sigma2, C) {
    .Call('_pmartRqc_group_comparison_anova_cpp', PACKAGE = 'pmartRqc', means, sizes, sigma2, C)
}

gtest_cpp <- function(data, gp) {
    .Call('_pmartRqc_gtest_cpp', PACKAGE = 'pmartRqc', data, gp)
}

holm_cpp <- function(ps) {
    .Call('_pmartRqc_holm_cpp', PACKAGE = 'pmartRqc', ps)
}

kw_rcpp <- function(mtr, group) {
    .Call('_pmartRqc_kw_rcpp', PACKAGE = 'pmartRqc', mtr, group)
}

nonmissing_per_grp <- function(mtr, group) {
    .Call('_pmartRqc_nonmissing_per_grp', PACKAGE = 'pmartRqc', mtr, group)
}

pooled_cv_rcpp <- function(mtr, group) {
    .Call('_pmartRqc_pooled_cv_rcpp', PACKAGE = 'pmartRqc', mtr, group)
}

#' @export
rcpp_hello_world <- function() {
    .Call('_pmartRqc_rcpp_hello_world', PACKAGE = 'pmartRqc')
}

ptukey_speed <- function(qstats, sizes) {
    .Call('_pmartRqc_ptukey_speed', PACKAGE = 'pmartRqc', qstats, sizes)
}

two_factor_anova_cpp <- function(y, X_full, X_red, red_df) {
    .Call('_pmartRqc_two_factor_anova_cpp', PACKAGE = 'pmartRqc', y, X_full, X_red, red_df)
}

