# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kw_rcpp <- function(mtr, group) {
    .Call('pmartRqc_kw_rcpp', PACKAGE = 'pmartRqc', mtr, group)
}

nonmissing_per_grp <- function(mtr, group) {
    .Call('pmartRqc_nonmissing_per_grp', PACKAGE = 'pmartRqc', mtr, group)
}

#' @export
rcpp_hello_world <- function() {
    .Call('pmartRqc_rcpp_hello_world', PACKAGE = 'pmartRqc')
}

