# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pooled_cv_rcpp <- function(mtr, group) {
    .Call('_pmartR_pooled_cv_rcpp', PACKAGE = 'pmartR', mtr, group)
}

unpooled_cv_rcpp <- function(mtr) {
    .Call('_pmartR_unpooled_cv_rcpp', PACKAGE = 'pmartR', mtr)
}

count_missing_cpp <- function(data, gp) {
    .Call('_pmartR_count_missing_cpp', PACKAGE = 'pmartR', data, gp)
}

fold_change_diff <- function(data, C) {
    .Call('_pmartR_fold_change_diff', PACKAGE = 'pmartR', data, C)
}

fold_change_diff_row <- function(means, C) {
    .Call('_pmartR_fold_change_diff_row', PACKAGE = 'pmartR', means, C)
}

fold_change_ratio <- function(data, C) {
    .Call('_pmartR_fold_change_ratio', PACKAGE = 'pmartR', data, C)
}

fold_change_diff_na_okay <- function(data, C) {
    .Call('_pmartR_fold_change_diff_na_okay', PACKAGE = 'pmartR', data, C)
}

anova_cpp <- function(data, gp, unequal_var, X, Beta, beta_to_mu, continuous_covar_inds, n_covar_levels) {
    .Call('_pmartR_anova_cpp', PACKAGE = 'pmartR', data, gp, unequal_var, X, Beta, beta_to_mu, continuous_covar_inds, n_covar_levels)
}

two_factor_anova_cpp <- function(y, X_full, X_red, group_ids, beta_to_mu_full, beta_to_mu_red, continuous_covar_inds, n_covar_levels) {
    .Call('_pmartR_two_factor_anova_cpp', PACKAGE = 'pmartR', y, X_full, X_red, group_ids, beta_to_mu_full, beta_to_mu_red, continuous_covar_inds, n_covar_levels)
}

group_comparison_anova_cpp <- function(means, data, sizes, which_xmatrix, Xfull, Xred, Cfull, Cred, Cmu) {
    .Call('_pmartR_group_comparison_anova_cpp', PACKAGE = 'pmartR', means, data, sizes, which_xmatrix, Xfull, Xred, Cfull, Cred, Cmu)
}

holm_cpp <- function(ps) {
    .Call('_pmartR_holm_cpp', PACKAGE = 'pmartR', ps)
}

ptukey_speed <- function(qstats, sizes) {
    .Call('_pmartR_ptukey_speed', PACKAGE = 'pmartR', qstats, sizes)
}

compute_betas <- function(data_mat, Xmatrix) {
    .Call('_pmartR_compute_betas', PACKAGE = 'pmartR', data_mat, Xmatrix)
}

kw_rcpp <- function(mtr, group) {
    .Call('_pmartR_kw_rcpp', PACKAGE = 'pmartR', mtr, group)
}

nonmissing_per_grp <- function(mtr, group) {
    .Call('_pmartR_nonmissing_per_grp', PACKAGE = 'pmartR', mtr, group)
}

